In [ ]:
# numpy 배열 브로드캐스팅 기능 
import numpy as np


In [10]:
#nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
nums = np.arange(1, 11)
"""
    np.arange(10) : 0~9
    np.arange(1, 11) : 1~10
    np.arange(1, 11, 2) : 1, 3, 5, 7, 9
"""
nums = nums + 10
nums = nums * 2
nums

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [ ]:
# 배열의 차원 변경, reshape
nums2 = nums.reshape(2, 5) # 2행 5열
nums2

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [12]:
nums3 = nums.reshape(5, 2) # 5행 2열 
nums3

array([[22, 24],
       [26, 28],
       [30, 32],
       [34, 36],
       [38, 40]])

In [ ]:
nums4 = nums.reshape(3, 3) 

ValueError: cannot reshape array of size 10 into shape (3,3)

In [15]:
#nums5 = nums.reshape(10, 1) 
nums5 = nums.reshape(-1, 1) # 전체 열을 전체 행의 갯수
nums5

array([[22],
       [24],
       [26],
       [28],
       [30],
       [32],
       [34],
       [36],
       [38],
       [40]])

In [16]:
nums

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [17]:
np.random.shuffle(nums)

In [18]:
nums

array([36, 26, 22, 40, 32, 28, 38, 30, 24, 34])