In [1]:
import pandas as pd
df = pd.read_csv('https://bit.ly/fish_csv_data')
df.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [2]:
import numpy as np

fish_data = df[['Weight', 'Length', 'Diagonal', 'Height', 'Width']].to_numpy()
fish_target = df['Species'].to_numpy()

In [3]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(
    fish_data, fish_target, test_size=0.2, random_state=42
)

In [4]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)

train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [5]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_scaled, train_target)

LogisticRegression()

In [6]:
lr.predict(test_scaled[:5])

array(['Perch', 'Smelt', 'Pike', 'Perch', 'Perch'], dtype=object)

In [7]:
lr.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [8]:
# 선형 방정식의 해를 구하면...
decision = lr.decision_function(test_scaled[:5])
decision

array([[-2.38693371,  0.73845627,  2.62170907, -1.71032535,  1.95713093,
         0.30882691, -1.52886411],
       [-4.27458833,  1.4136374 ,  2.20310822, -2.0582524 ,  1.7763688 ,
         3.90486184, -2.96513553],
       [-1.51449968, -1.53405617,  1.75052568,  2.7254744 ,  1.58136534,
        -1.92366845, -1.08514112],
       [ 0.04331012,  0.24157064,  2.2189273 , -0.51402595,  1.54580718,
        -3.13897903, -0.39661026],
       [-2.26143971, -0.33241143,  2.93050844, -0.40268582,  1.95714483,
        -0.81002758, -1.08108873]])

In [11]:
# 분류하려면 각 클래스마다 구해진 해의 비율 - 소프트맥스 
from scipy.special import softmax
np.round(softmax(decision, axis=1), decimals=3)

array([[0.004, 0.084, 0.555, 0.007, 0.286, 0.055, 0.009],
       [0.   , 0.06 , 0.131, 0.002, 0.086, 0.72 , 0.001],
       [0.008, 0.008, 0.215, 0.569, 0.181, 0.005, 0.013],
       [0.06 , 0.073, 0.525, 0.034, 0.268, 0.002, 0.038],
       [0.004, 0.026, 0.667, 0.024, 0.252, 0.016, 0.012]])

In [14]:
np.round(lr.predict_proba(test_scaled[:5]), decimals=3)

array([[0.004, 0.084, 0.555, 0.007, 0.286, 0.055, 0.009],
       [0.   , 0.06 , 0.131, 0.002, 0.086, 0.72 , 0.001],
       [0.008, 0.008, 0.215, 0.569, 0.181, 0.005, 0.013],
       [0.06 , 0.073, 0.525, 0.034, 0.268, 0.002, 0.038],
       [0.004, 0.026, 0.667, 0.024, 0.252, 0.016, 0.012]])