In [1]:
from scipy.stats import randint, uniform

In [2]:
ri = randint(0, 10) # 0~9 무작위 수
ri.rvs(11) # 0~9사이 숫자 중 무작위 수를 11개 생성 

array([4, 5, 4, 4, 6, 9, 6, 3, 9, 9, 8])

In [5]:
import numpy as np

np.unique(ri.rvs(1000), return_counts=True) # 중복된 총 갯수를 함께 반환 

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([118, 117,  98,  92,  88,  90, 104,  98,  99,  96]))

In [6]:
ui = uniform(0, 1) # 0~1 사이의 무작위 실수
ui.rvs(5) # 0~1 사이 무작위 실수를 5개 생성

array([0.17107306, 0.08469249, 0.03774359, 0.2513111 , 0.9393748 ])